const BASE_HUE = 90;
const HUE_STEP = 30;
const BACKGROUND_SATURATION = 70;
const BACKGROUND_LIGHTNESS = 70;
const ANIMATION_DURATION_MULTIPLIER = 300;
const DEGREES_IN_CIRCLE = 360;

export const UseHomeScreenConstants = {
  BASE_HUE,
  HUE_STEP,
  BACKGROUND_SATURATION,
  BACKGROUND_LIGHTNESS,
  ANIMATION_DURATION_MULTIPLIER,
  DEGREES_IN_CIRCLE,
};
