const BASE_HUE = 90;
const HUE_STEP = 30;
const TEXT_HUE_OFFSET = 30;
const BACKGROUND_SATURATION = 70;
const BACKGROUND_LIGHTNESS = 70;
const TEXT_SATURATION = 70;
const TEXT_LIGHTNESS = 20;
const ANIMATION_DURATION = 700;

export const ColorsConfig = {
  BASE_HUE,
  HUE_STEP,
  TEXT_HUE_OFFSET,
  BACKGROUND_SATURATION,
  BACKGROUND_LIGHTNESS,
  TEXT_SATURATION,
  TEXT_LIGHTNESS,
  ANIMATION_DURATION,
};
